# Function to create the modal dialog
createCodeModal = function() {
  modalDialog(
    verbatimTextOutput("showCode", placeholder = FALSE),
    footer = tagList(
      modalButton("Close"),
      #actionButton("copyCode", "Copy", class = "btn btn-success"),
      downloadButton("saveCode", "Save", class="btn btn-info")
    )
  )
}

vec2ascii = function(x) {
  if(is.character(x))
    x = paste0('"', x, '"')
  if(length(x) == 0)
    return(NULL)
  if(length(x) == 1)
    return(x)
  sprintf("c(%s)", toString(x))
}

validName = function(nms) {
  invalid = make.names(nms) != nms
  if(any(invalid))
    nms[invalid] = sprintf("`%s`", nms[invalid])
  nms
}

namedvec2ascii = function(x) {
  if(is.character(x))
    x[] = paste0('"', x, '"')
  args = glue("{validName(names(x))} = {x}")
  sprintf("c(%s)", toString(args))
}

generateCode = function(ped, twins = NULL, styles = NULL, textAnnot = NULL, cex = 1, symbolsize = 1, margins = 1,
                        width, height) {
  pedDf = as.data.frame(ped)

  params = c(glue("x, cex = {cex}, symbolsize = {symbolsize}, margins = {margins}"),
    if(!is.null(styles$hatched)) glue("hatched = {vec2ascii(sortIds(ped, styles$hatched))}"),
    if(!is.null(styles$carrier)) glue("carrier = {vec2ascii(sortIds(ped, styles$carrier))}"),
    if(!is.null(styles$deceased)) glue("deceased = {vec2ascii(sortIds(ped, styles$deceased))}"),
    if(!is.null(styles$dashed)) glue("lty = list(`2` = {vec2ascii(sortIds(ped, styles$dashed))})"),
    if(!is.null(styles$fill)) glue("fill = {namedvec2ascii(styles$fill)}"),
    NULL
  )

  # Text annotations (list)
  if(!is.null(textAnnot <- formatAnnot(textAnnot, cex = cex))) {
    txtAnnList = sapply(names(textAnnot), function(a) {
      anna = textAnnot[[a]]
      vec1 = namedvec2ascii(anna[[1]])
      pars = unlist(anna[-1])
      ischar = is.na(suppressWarnings(as.numeric(pars)))
      pars[ischar] = paste0('"', pars[ischar], '"')
      txtPars = toString(glue("{validName(names(pars))} = {pars}"))
      glue("{a} = list({vec1}, {txtPars})")
    })
    txtAnnChar = glue_collapse(txtAnnList, sep = ",\n              ")
    txtAnn = glue('\n
    # Text annotations
    textAnnot = list({txtAnnChar})\n
    ')
    params = c(params, glue("textAnnot = textAnnot"))
  }
  else
    txtAnn = ""

  # Complete text template
  txt = '
  #########################################
  # R code reproducing a QuickPed plot
  #
  # Generated by QuickPed, {format(lubridate::now(),"%Y-%m-%d %H:%M")}
  # https://magnusdv.shinyapps.io/quickped/
  #########################################

  # Load package
  library(pedtools)

  # Pedigree
  x = ped(id  = {vec2ascii(pedDf$id)},
          fid = {vec2ascii(pedDf$fid)},
          mid = {vec2ascii(pedDf$mid)},
          sex = {vec2ascii(pedDf$sex)})
  {txtAnn}
  # Plot
  plot({glue_collapse(params, sep = ",\n       ")})
  '

  # Glue and return
  glue(txt)
}
